Repository gleanwork/mcp-server, pull requests merged in 2025-05, with the labels that each got.

#97 chore: Bumping node, pinning to lowest version, updating ci matrix
  .github/workflows/ci.yml
  package.json
Labels: breaking

#125 feat(configure): add VS Code MCP client support
  README.md
  src/configure.ts
  src/configure/client/vscode.ts
  src/configure/index.ts
  src/test/cli.test.ts
  src/test/configure/vscode.test.ts
Labels: enhancement

#132 fix(cli): Fixes .env file and process.env support in configure
  .vscode/launch.json
  src/configure.ts
  src/index.ts
  src/test/cli.test.ts
  src/test/validate-flags.test.ts
Labels: bug
