Repository gleanwork/mcp-server, pull requests merged in 2025-06, with the labels that each got.

#171 fix(auth): keep unexpired refresh tokens
  packages/mcp-server-utils/src/auth/token-store.ts
  packages/mcp-server-utils/src/test/auth/auth.test.ts
Labels: bug

#174 fix(release): Ensure `pnpm-lock.yaml` is updated on release
  package.json
  pnpm-lock.yaml
Labels: internal

#177 fix: Don't include GLEAN_INSTANCE for remote
  packages/configure-mcp-server/src/configure/client/index.ts
  packages/configure-mcp-server/src/test/cli.test.ts
  packages/configure-mcp-server/src/test/configure.test.ts
  packages/configure-mcp-server/src/test/configure/vscode.test.ts
Labels: bug

#181 feat: rework success message
  packages/configure-mcp-server/src/configure/client/index.ts
  packages/configure-mcp-server/src/configure/client/vscode.ts
  packages/configure-mcp-server/src/test/cli.test.ts
Labels: documentation

#182 Enable OAuth by default (without environment variable)
  packages/configure-mcp-server/src/common/env.ts
  packages/configure-mcp-server/src/configure/index.ts
  packages/configure-mcp-server/src/test/cli.test.ts
  packages/configure-mcp-server/src/test/configure.test.ts
Labels: enhancement

#163 [tool] Add read_documents MCP tool for retrieving documents by ID or URL
  packages/local-mcp-server/README.md
  packages/local-mcp-server/src/server.ts
  packages/local-mcp-server/src/test/tools/read_documents.test.ts
  packages/local-mcp-server/src/tools/read_documents.ts
Labels: enhancement

#192 chore(release): Ensure releaser has ran `pnpm login`
  package.json
  pnpm-lock.yaml
Labels: internal

#199 Fix remote token header
  packages/configure-mcp-server/src/configure/client/goose.ts
  packages/configure-mcp-server/src/configure/client/index.ts
  packages/configure-mcp-server/src/test/cli.test.ts
  packages/configure-mcp-server/src/test/configure.test.ts
  packages/configure-mcp-server/src/test/configure/vscode.test.ts
Labels: bug, codex

#200 Refactor goose client config
  packages/configure-mcp-server/package.json
  packages/configure-mcp-server/src/configure/client/goose.ts
  packages/configure-mcp-server/src/configure/client/index.ts
Labels: codex
